nome = str(input('Nome: '))
idade = int(input('Idade: '))
peso = float(input('Peso: '))
altura = float(input('Altura: '))
n_sus = str(input('Número do SUS:'))
diagnostico = str(input('Diagnostico: '))
print(f'{nome},{idade},{peso},{altura},{n_sus},{diagnostico}')